# Generated by Django 4.1.13 on 2024-05-03 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_post_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
